[project]
name = "mar-16-code-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "claudette>=0.1.4",
    "pandas>=2.2.3",
    "psycopg2-binary>=2.9.10",
]

[dependency-groups]
dev = [
    "ipython>=8.34.0",
]
